In [168]:
##  标准化
#########################################################################################
from sklearn import preprocessing
import numpy as np
X = np.array([[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]])
x_scaled = preprocessing.scale(X)
print("标准化\n",x_scaled)
print("均值\n",x_scaled.mean(axis=0))
print("方差\n",x_scaled.std(axis=0))

标准化
 [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
均值
 [0. 0. 0.]
方差
 [1. 1. 1.]


In [124]:
##  标准化
#########################################################################################
from sklearn import preprocessing
import numpy as np
X = np.array([[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]])
X_scaled = preprocessing.StandardScaler().fit(X)
#X_scaled
new_x = np.array([[ 1., -4.,2.],[ 1.,  10.,  0.],[ 30.,  12., -1.5]])
X_scaled.fit_transform(new_x)

array([[-0.70710678, -1.40487872,  1.27872403],
       [-0.70710678,  0.56195149, -0.11624764],
       [ 1.41421356,  0.84292723, -1.16247639]])

In [122]:
##  标准化
#########################################################################################
from sklearn import preprocessing
import numpy as np
X = np.array([[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]])
new_x = np.array([[1.1,1.2,1.3],[2.4,2.5,2.6]])
X_stdscaler = preprocessing.StandardScaler()
X_stdscaler.fit_transform(new_x)

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [123]:
##  标准化
#########################################################################################
from sklearn import preprocessing
import numpy as np
X = np.array([[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]])
X_MmS = preprocessing.MinMaxScaler().fit(X)
result = X_MmS.transform(X)
result

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [43]:
##  正则化
#########################################################################################
from sklearn import preprocessing
import numpy as np
X = np.array([[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]])
X_scaled = preprocessing.Normalizer()
X_normalizer = X_scaled.transform(X)
X_normalizer

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [164]:
## 特征二值化
#########################################################################################
from sklearn.preprocessing import Binarizer
import numpy as np
bin = Binarizer()
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[0,5,9]])
bin.fit(x)
bin.transform(y)

array([[0, 1, 1]])

In [91]:
##  编码分类特征
#########################################################################################
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np
X = [ 1., 2.,  3. ,4. ,5. ,6. ]
X_Label = LabelEncoder().fit(X)
result = X_Label.transform([1., 2., 2., 4. ])
result

array([0, 1, 1, 3], dtype=int64)

In [95]:
##  编码分类特征
#########################################################################################
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np
X = np.array([ 1, 3,  2])
X_Label = OneHotEncoder()
X_Label1 = X_Label.fit_transform(X.reshape(-1,1)).toarray()
X_Label1

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [144]:
##  缺失值处理
##########################################################################################
from sklearn.preprocessing import Imputer
import numpy as np
imp = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imp.fit([[1,2,np.nan],[np.nan,4,6],[3,np.nan,9]])
X = [[1,2,np.nan],[np.nan,4,6],[3,np.nan,9]]
result = imp.transform(X)
result

array([[1. , 2. , 7.5],
       [2. , 4. , 6. ],
       [3. , 3. , 9. ]])

In [150]:
##  创建多项式特征
#########################################################################################
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X=np.arange(6).reshape(3,2)
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [159]:
##  自定义特征的转换函数
#########################################################################################
from sklearn.preprocessing import FunctionTransformer
import numpy as np
fun = FunctionTransformer(np.log1p)
x = np.array([[0,1],[2,3],[2.718,10]])
fun.fit_transform(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.31318589, 2.39789527]])

In [183]:
##  非线性变化
#########################################################################################
import numpy as np
from sklearn.preprocessing import QuantileTransformer
rng = np.random.RandomState(0)
X = np.sort(rng.normal(loc=0.5, scale=0.25, size=(7, 1)), axis=0)
qt = QuantileTransformer(n_quantiles=10, random_state=0)
qt.fit_transform(X) 

array([[9.99999998e-08],
       [1.90519132e-01],
       [3.33333333e-01],
       [4.48355287e-01],
       [6.66666667e-01],
       [8.01896154e-01],
       [9.99999900e-01]])

In [217]:
##  离散化
#########################################################################################
from sklearn.preprocessing import KBinsDiscretizer
import numpy as np
X = np.array([[ -3., 5., 15 ],[  0., 6., 14 ],[  6., 3., 11 ]])
est = KBinsDiscretizer().fit(X)
XT = est.transform(X)
XT

ImportError: cannot import name 'KBinsDiscretizer' from 'sklearn.preprocessing' (D:\Anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

In [165]:
##  编程题
# 本题目中a,b分别被定义为OneHotEncoder()类和LabelEncoder()类，
# 而首先传入的数据是[123,456,789],并在b处理后(b.fit_transform)传给temp变量，得到[0,1,2]向量。
# 并将此结果作为a的特征输入(a.fit)，之后对特征[123,789]进行a类型编码(a.transform)，
# 得到result的结果，最终将temp和result显示出来，得到如下结果。
#########################################################################################
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np
a_array = np.array([123,456,789])
b_array = np.array([123,789])
a = OneHotEncoder()
b = LabelEncoder()
temp = b.fit_transform(a_array)
temp.reshape(-1,1)
a.fit(temp.reshape(-1,1))
result = a.transform(b.transform(b_array).reshape(-1,1)).toarray()
print(temp)
result

[0 1 2]


array([[1., 0., 0.],
       [0., 0., 1.]])