In [1]:
# 使用sklearn.preprocessing.scale()函数，将给定数据进行标准化
from sklearn import preprocessing
import numpy as np
X = np.array([[ 1., -1.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])
X_scaled = preprocessing.scale(X)
 
X_scaled  

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [2]:
# 处理后数据的均值
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [4]:
# 处理后数据的方差
X_scaled.std(axis=0)

array([1., 1., 1.])

In [5]:
# 明白 axis=0 是按列；  axis=1 是按行